services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://fileuser:filepass@db:5432/file_sharing_db
      - SECRET_KEY=your-secret-key-here-make-it-long-and-random
      - DEBUG=true
      - HOST=0.0.0.0
      - PORT=8000
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=your-email@gmail.com
      - SMTP_PASSWORD=your-app-password
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=file_sharing_db
      - POSTGRES_USER=fileuser
      - POSTGRES_PASSWORD=filepass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: 